### ISSUE TITLE
Assertion Error in Machine Translation tab

### ISSUE THREAD

**Issue by miguelemosreverte** [roxana-lafuente/TTT#13]
When using the machine translation tab wrong, that is straight up selecting a file and asking for it to be translated, the following error shows:
```

Traceback (most recent call last):
  File "main.py", line 774, in _machine_translation
    adapt_path_for_cygwin(self.is_windows, self.output_text.get_text()) + "/train/model/moses.ini",
  File "/home/migue/TTT/constants.py", line 39, in adapt_path_for_cygwin
    assert len(directory) > 0
AssertionError
```
Possible solutions:
Maybe a friendlier error message could be shown? 
Not to allow the user to ask for translation if its going to cause an error

**Comment by roxana-lafuente** [comment]
Done. Now it shows the following message: "ERROR. You need to load or create a model first."
