### ISSUE TITLE
Why sometimes the deletions and insertions differ

### ISSUE THREAD

**Issue by miguelemosreverte** [roxana-lafuente/TTT#19]
Say I have a log where I saved a ton of u's in a segment: 
![screenshot from 2017-01-25 23-13-52](https://cloud.githubusercontent.com/assets/9152392/22317797/dc72900a-e354-11e6-81b3-01855a8a8e8f.png)

When I come back in a different TTT session, and add another "u" in the middle of the u's, the statistics do not show any insertion made to the segment

**Comment by miguelemosreverte** [comment]
The reason is that when using TTT multiple times, and using the same output folder, then the same log is used, and right now it seems like the Differences tab, alongside with the real contents of the table, is correctly inferred from the log, accumulating the changes made in the last post-editing sessions.

Now, there definitely is a problem with the Statistics tab: It is inferring the modified segments content just from the changes made on the current session.

Some of the possible solutions are:
1 To load the log, during initialization, just like PostEdition and subsequently Differences already do.
2 To get the source and modified segment contents directly from PostEdition, already correctly inferred

**Comment by miguelemosreverte** [comment]
When checking the difference between two texts, character by character, there are two main differences that stand out: The first one would be the insertion and deletion of information. The second one the replacing of it. When taking replacement into account then it happens what is shown in the Differences tab, the moving of a word far way from its original place, by hitting whitespace, is colored green. The whitespaces are not colored, they are the inserted characters, and are invisible to the human eye! But the moved words? They get colored just like the whitespaces would, because they have been _replaced._

Now about statistics: 
When looking at the stats, say the insertion stats for example, you must be asking yourself how many characters have been actually inserted, not moved from their original location. Same with the deletion stats, the replaced characters get ignored. 

Problem is, when you add a letter "u" in the middle of a sea of "u" 's, you are in for a bad time then, because the difference calculator will see a "u" where another "u" was on its place, and will assume no change has been made to that character. But then it will know that the letters to the right have been moved, and taken the place from the letters before them, right? Remember that the replacement of characters is being ignored to achieve strict insertion and deletion percentages: no insertions there either, and you got then your final result: A statistics calculator that is visibly wrong sometimes.

**Comment by miguelemosreverte** [comment]
Anyhow, multiple tests of this very problem have convinced me it was the lack of sleep and not the code what was causing the problem. Still got a kick out if it, though, and wrote a good few ideas, but because the bug has not been reproduced, the problem is considered solved.

_Post of an unnecessary gif to convince the non-believers that come across this Issue and see my answers:_ See how the Differences and Statistics tab only appear after saving the change: This definitely is a fresh new TTT session, with a recovered log loaded, and a sea of 'r' in which to prove that adding one more 'r' will now cause any problem.
![out](https://cloud.githubusercontent.com/assets/9152392/22318921/258c179a-e35d-11e6-98a0-5d65d72e8a82.gif)

**Comment by miguelemosreverte** [comment]
Okay, this Issue is getting opened again.
It seems like choosing not to compare the _replaced_ characters is causing the insertion statistics to think that if a word have been erased and a single letter been placed in its place, then it does not count as an insertion of a single letter. Its completely wrong!

here is how the Differences tab compares the two segments: (taking into account the _replaced_ characters)
![screenshot from 2017-02-01 23-11-06](https://cloud.githubusercontent.com/assets/9152392/22534597/d224e9d4-e8d3-11e6-8f45-4052e951fa44.png)

but the insertion statistics say that no insertion has been done to the segment!

**Comment by miguelemosreverte** [comment]
Okay, it seems that taking the _replaced_ characters during the insertion stats calculation works, since its what the Differences tab actually does. Case closed!

![screenshot from 2017-02-01 23-13-23](https://cloud.githubusercontent.com/assets/9152392/22534657/3a546c6e-e8d4-11e6-967c-765d818db635.png)

**Comment by roxana-lafuente** [comment]
Did this happen in master? Is it necessary any modification?

**Comment by miguelemosreverte** [comment]
Its been fixed, and yes it ocurred anywhere statistics where calculated without taking the _replaced_ characters into account. Now they do, and work just like the Differences tab does: Before their behaviour was different given that statistics ignored the _replaced_ characters, and only worked with the _inserted_ characters for the insertion statistics, and the _deleted_ characters for the deletion statistics.
