### ISSUE TITLE
When performing a MT, the output is saved in the /home dir

### ISSUE THREAD

**Issue by roxana-lafuente** [roxana-lafuente/TTT#20]
Instead, it should be saved in the output directory.

**Comment by miguelemosreverte** [comment]
Right now it is saved to where the text you are translating actually is, and it does so by design, (ask to the Switzerland team). This should come across more as a possible enhancement if anything.

**Comment by miguelemosreverte** [comment]
> Instead, it should be saved in the output directory.

Evidently this is more of an enhancement than a bug. Will be changing the label accordingly.
