### ISSUE TITLE
Program should start on "Corpus Preparation" tab

### ISSUE THREAD

**Issue by roxana-lafuente** [roxana-lafuente/TTT#3]
Program should start on "Corpus Preparation" tab, instead it is starting on "Machine Translation" tab

**Comment by miguelemosreverte** [comment]
It was not my idea, but Paula's, to have it start at machine translation, and to go different ways from there. And I like the idea so we win by numbers, it seems like.

![](https://cdn.meme.am/cache/images/folder927/300x/12352927.jpg)
