### ISSUE TITLE
In "Evaluation" tab, problem with HTER and GTM

### ISSUE THREAD

**Issue by roxana-lafuente** [roxana-lafuente/TTT#8]
When you choose two identical files (source text and reference), HTER and GTM are empty. Should it show an error message or a value?

**Comment by miguelemosreverte** [comment]
They should, but where filtered until now. HTER, specifically has a lot to say about using identical iles for source and reference. GTM on the other hand dose so, too, but on a smaller scale, and for some reason, unbeknownst to me, directly to console.

**Comment by miguelemosreverte** [comment]
So it is not a bug, it was a feature. Until now to filter the output of the evaluation scripts was a desired thing.
